# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bkpfiev.com:
  peer0.exporterorg.bkpfiev.com:
  peer0.importerorg.bkpfiev.com:
  peer0.carrierorg.bkpfiev.com:
  peer0.regulatororg.bkpfiev.com:
  peer0.supermarketorg.bkpfiev.com:
  peer0.farmerorg.bkpfiev.com:

networks:
  byfn:

services:

  orderer.bkpfiev.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bkpfiev.com
    container_name: orderer.bkpfiev.com
    networks:
      - byfn

  peer0.exporterorg.bkpfiev.com:
    container_name: peer0.exporterorg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporterorg.bkpfiev.com
    networks:
      - byfn

  peer0.importerorg.bkpfiev.com:
    container_name: peer0.importerorg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerorg.bkpfiev.com
    networks:
      - byfn

  peer0.carrierorg.bkpfiev.com:
    container_name: peer0.carrierorg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.carrierorg.bkpfiev.com
    networks:
      - byfn

  peer0.regulatororg.bkpfiev.com:
    container_name: peer0.regulatororg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.regulatororg.bkpfiev.com
    networks:
      - byfn
    
  peer0.supermarketorg.bkpfiev.com:
    container_name: peer0.supermarketorg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supermarketorg.bkpfiev.com
    networks:
      - byfn

  peer0.farmerorg.bkpfiev.com:
    container_name: peer0.farmerorg.bkpfiev.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.farmerorg.bkpfiev.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.exporterorg.bkpfiev.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.bkpfiev.com/peers/peer0.exporterorg.bkpfiev.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.bkpfiev.com/peers/peer0.exporterorg.bkpfiev.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.bkpfiev.com/peers/peer0.exporterorg.bkpfiev.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.bkpfiev.com/users/Admin@exporterorg.bkpfiev.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bkpfiev.com
      - peer0.exporterorg.bkpfiev.com
      - peer0.importerorg.bkpfiev.com
      - peer0.carrierorg.bkpfiev.com
      - peer0.regulatororg.bkpfiev.com
      - peer0.supermarketorg.bkpfiev.com
      - peer0.farmerorg.bkpfiev.com
    networks:
      - byfn
